name: turista_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Mapa e localização
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Localização e permissões
  geolocator: ^14.0.2
  geocoding: ^2.2.0
  permission_handler: ^12.0.1

  # SQLite (Banco de dados local)
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.2 # apenas se usar getApplicationDocumentsDirectory()

  # Google Maps (pronto para uso futuro)
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
